# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b444319713513e4cc41f29a773a7c3cf6e1ac21d852ce6dd6de9be3fce5d74d87966cd5f633af3377f0cda5e1c022a222dd19382f91ab66c7bfaf5c6d831706d

test:
  secret_key_base: 66b6a4954261e3b31c869493d190bfd695cd1659f5b8cf589db46a65a7a88e556cf4233d2a115dc1e333f00ebfe81f1c5bfd4e1ae268896b6b5091618beedefe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
